config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :logs do
  	collection { post :import }
	end
  root "logs#index"
  
end

app/models/log.rb
class Log < ActiveRecord::Base
	belongs_to :user

	validates :amount, numericality: true

	audited

MAPPING = {
	"Record ID" => "id",
	"Chq Number" => "chq_number",
	"Chq Date" => "chq_date",
	"Payee Name" => "payee_name",
	"Category" => "category",
	"Deal ID" => "deal_id",
	"Particular" => "particular",
	"Salesperson" => "salesperson",
	"Voucher Number" => "voucher_no",
	"Currencies" => "currencies",
	"Amount" => "amount",
	"Prepared by" => "prepared",
	"Signed Chq Date" => "sign_date",
	"Chq Presented Date" => "present_date",
	"Void Chq Reason" => "void_reason"
}

	def self.import(file)
	  spreadsheet = open_spreadsheet(file)
	  header = spreadsheet.row(1)
	  (2..spreadsheet.last_row).each do |i|
	    row = Hash[[header, spreadsheet.row(i)].transpose]
	    row.keys.each { |k| row[ MAPPING[k] ] = row.delete(k) if MAPPING[k] }
	    log = find_by_id(row["id"]) || new
	    log.attributes = row.to_hash.slice(*row.to_hash.keys)
	    log.save!
	  end
	end

	def self.open_spreadsheet(file)
	  case File.extname(file.original_filename)
	  when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
	  when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
	  when ".xlsx" then Roo::Excelx.new(file.path, packed: false, file_warning: :ignore)
	  else raise "Unknown file type: #{file.original_filename}"
	  end
	end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

 	has_many :logs

 	audited
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :authorize_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @q = Log.ransack(params[:q])
    @logs = @q.result(distinct: true).order("created_at DESC")

    respond_to do |format|
      format.html do
        @logs = @logs.paginate(:page => params[:page], :per_page => 100)
      end
      format.xlsx do
        render xlsx: 'index', filename: "Chq_log.xlsx"
      end
    end
  end

  def show
  end

  def new    
    @log = current_user.logs.build
    @log.prepared = current_user.name
  end

  def edit
  end

  def create
    @log = current_user.logs.build(log_params)
    @log.prepared = current_user.name

    respond_to do |format|
      if @log.save
        format.html { redirect_to root_path, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to @log, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Log.import(params[:file])
    redirect_to root_url, notice: "Records imported."
  end

  private
  
  def set_log
    @log = Log.find(params[:id])
  end

  def log_params
    params.require(:log).permit(:chq_number, :chq_date, :payee_name, :category, :deal_id, :particular, :prepared, :currencies, :amount, :sign_date, :present_date, :status, :salesperson, :voucher_no, :void_reason)
  end

  def authorize_user!
    if current_user.viewer?
      flash[:alert] = 'You are not allowed to access this page.'
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Payment Log" , root_path , class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to root_path do%>
              <span class="glyphicon glyphicon-list-alt"></span> View Record
            <% end %>
          </li>
          <% if not current_user.viewer? %>
            <li>
              <%= link_to new_log_path, 'data-no-turbolink' => true do %>
                <span class="glyphicon glyphicon-plus"></span> Add Record
              <% end %>
            </li>
            
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-upload"></span> Import Record
              </a>
                <ul class="dropdown-menu">
                  <%= render 'upload'%>
                </ul>
            </li>
          <% end %>

          <li>
            <%= link_to destroy_user_session_path, method: :delete do%>
              <span class="glyphicon glyphicon-user"></span> Log Out
            <% end %>
          </li>

        <% else %>

          <li>
            <%= link_to new_user_session_path do%>
            <span class="glyphicon glyphicon-user"></span> Login
            <% end %>
          </li>
        <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  </div><!-- /.container --> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Payment Log</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>

		<%= yield %>
	</div>

</body>
</html>

app/views/logs/_form.html.erb
<%= form_for(@log) do |f| %>
  <% if @log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% @log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-md-4">
    <div class="field">
      <%= f.label :chq_number %><br>
      <%= f.text_field :chq_number, required: true %>
    </div>
  </div>

  <div class="col-md-4">
    <div class="field">
      <%= f.label :chq_date %><br>
      <%= f.text_field :chq_date, required: true, 'data-behaviour' => 'datepicker' %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="field">
      <%= f.label :payee_name %><br>
      <%= f.text_field :payee_name, required: true %>
    </div>
  </div>
  
  <div class="col-md-4">
    <div class="field">
      <%= f.label :category %><br>
      <% if @log.new_record? %>
        <%= f.select :category, options_for_select([['OP'],['Deal'],['Sourcing'],['Lux'],['COS'],['Health'],['XB'],['SME2C'],['Refund'],['Others']], params[:category]), {} %>
      <% else %>
        <%= f.select :category, options_for_select([['OP'],['Deal'],['Sourcing'],['Lux'],['COS'],['Health'],['XB'],['SME2C'],['Refund'],['Others']], :selected => f.object.category), {} %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="field">
      <%= f.label :deal_id %><br>
      <%= f.text_field :deal_id, required: false %>
    </div>
  </div>

  <div class="col-md-4">
    <div class="field">
      <%= f.label :particular %><br>
      <%= f.text_field :particular, required: true %>
    </div>
  </div>

  <div class="col-md-4">
    <div class="field">
      <%= f.label :salesperson %><br>
      <%= f.text_field :salesperson, required: false %>
    </div>
  </div>
  
</div>
  
<div class="row">
  <div class="col-md-4">
    <div class="field">
      <%= f.label :amount %><br>
      <% if @log.new_record? %>
        <%= f.select :currencies, options_for_select([['HKD'],['USD'],['EUR'],['CAD'],['SGD'],['AUD'],['MYR'],['RMB'],['KRW'],['GBP']], params[:currencies]), {} %>
      <% else %>
        <%= f.select :currencies, options_for_select([['HKD'],['USD'],['EUR'],['CAD'],['SGD'],['AUD'],['MYR'],['RMB'],['KRW'],['GBP']], :selected => f.object.currencies), {} %>
      <% end %>
      <%= f.text_field :amount, required: true %>
    </div>
  </div>

  <div class="col-md-4"></div>

  <div class="col-md-4">
    <%= f.label :voucher_no, "Voucher#" %><br>
    <%= f.text_field :voucher_no, required: false %>
  </div>
</div>


  <div class="field">
    <%= f.label :prepared, "Prepared by" %><br>
    <%= f.text_field :prepared, disabled: true %>
  </div>

<div class="row">
  <div class="col-md-4">
    <div class="field">
      <%= f.label :sign_date, "Signed Cheque Date" %><br>
      <%= f.text_field :sign_date, required: false, 'data-behaviour' => 'datepicker' %>
    </div>
  </div>

  <div class="col-md-4">
    <div class="field">
      <%= f.label :present_date, "Cheque Presented Date" %><br>
      <%= f.text_field :present_date, required: false, 'data-behaviour' => 'datepicker' %>
    </div>
  </div>

  <div class="col-md-4">
    <div class="field">
      <%= f.label :void_reason, "Void Cheque Reason" %><br>
      <%= f.text_field :void_reason, required: false %>
    </div>
  </div>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logs/_search.html.erb
<br>
<%= search_form_for @q do |f| %>
  
  <div class="form-group">
    <%= f.label :chq_number_eq %><br>
    <%= f.search_field :chq_number_eq %>
  </div>

  <div class="form-group">
    <%= f.label :payee_name_cont %><br>
    <%= f.search_field :payee_name_cont %>
  </div>

  <br>
  <br>
  <div class="form-group">
    <%= f.label :sign_date_gteq , "Sign Chq Date Start from:"%><br>
    <%= f.text_field :sign_date_gteq, 'data-behaviour' => 'datepicker' %>     

    <%=f.label :sign_date_lteq, "to" %>   
    <%= f.text_field :sign_date_lteq, 'data-behaviour' => 'datepicker' %>
  </div>

  <br>
  <br>
  <div class="form-group">
    <%= f.label :present_date_gteq , "Chq Presented Date Start from:"%><br>   
    <%= f.text_field :present_date_gteq, 'data-behaviour' => 'datepicker' %>     

    <%=f.label :present_date_lteq, "to" %>   
    <%= f.text_field :present_date_lteq, 'data-behaviour' => 'datepicker' %>
  </div>

  <br>
  <br>
  <div class="form-group">
    <%= f.label :category_eq , "Search by Category:"%><br>   
    <%= f.select :category_eq, options_for_select([[''],['OP'],['Deal'],['Sourcing'],['Lux'],['COS'],['Health'],['XB'],['SME2C'],['Refund'],['Others']], params[:category_eq]), {} %>
  </div>

  <br>
  <br>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>

  <%= link_to "Clear", root_path, class: "btn btn-default" %>

<% end %>

<br>

app/views/logs/_upload.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Import Record</h3>
  </div>
  <div class="panel-body">
    <%= form_tag import_logs_path, multipart: true do %>
		  <%= file_field_tag :file%><br>
		  <%= submit_tag "Upload", class: "btn btn-warning" %>
		<% end %>
  </div>
</div>

app/views/logs/edit.html.erb
<div class="panel panel-default">
	<div class="panel-heading"><h2>Update Log</h2></div>
	<div class="panel-body">
		<%= render 'form' %>
	</div>

	<div class="panel-footer">
		<%= link_to 'Back', logs_path %>
	</div>
</div>

app/views/logs/index.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal">
  Search
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Search</h4>
      </div>
      <div class="modal-body">
        <%= render 'search' %>
      </div>
    </div>
  </div>
</div>
<%= link_to "Show ALL", root_path, class: "btn btn-default" %>
<%= link_to "Export", url_for(params.merge(format: :xlsx)), class: "btn btn-success" %>


<table class="table">
  <thead>
    <tr>
      <th>Chq number</th>
      <th>Chq date</th>
      <th>Payee Name</th>
      <th>Category</th>
      <th>Deal</th>
      <th>Particular</th>
      <th>Salesperson</th>
      <th>Currencies</th>
      <th>Amount</th>
      <th>Prepared by</th>
      <th>Sign chq date</th>
      <th>Chq Presented date</th>
      <% if not current_user.viewer? %>
        <th colspan="3"></th>
      <% else %>
      <th colspan="1"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @logs.each do |log| %>
      <% if log.void_reason.present? %>
        <tr class="danger">
      <% elsif log.present_date.present? %>
        <tr class="success">
      <% else %>
        <tr>
      <% end %>
        <td><%= log.chq_number %></td>
        <td><%= log.chq_date %></td>
        <td><%= log.payee_name %></td>
        <td><%= log.category %></td>
        <td><%= log.deal_id %></td>
        <td><%= log.particular %></td>
        <td><%= log.salesperson %></td>
        <td><%= log.currencies %></td>
        <td><%= number_to_currency(log.amount, :unit => "") %></td>
        <td><%= log.prepared %></td>
        <td><%= log.sign_date %></td>
        <td><%= log.present_date %></td>
        
        <td>
          <%= link_to log, class: 'btn btn-success btn-xs' do %>
            <span class="glyphicon glyphicon-eye-open"></span>
          <% end %>
        </td>

        <% if not current_user.viewer? %>
          <td>
            <%= link_to edit_log_path(log), class: 'btn btn-warning btn-xs' do %>
              <span class="glyphicon glyphicon-edit"></span>
            <% end %>
          </td>

          <td>
            <%= link_to log, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' do %>
              <span class="glyphicon glyphicon-trash"></span>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
   <%= will_paginate @logs, renderer: BootstrapPagination::Rails %>
</div>

app/views/logs/new.html.erb
<div class="panel panel-default">
	<div class="panel-heading"><h2>Add New Record</h2></div>
	<div class="panel-body">
		<%= render 'form' %>
	</div>

	<div class="panel-footer">
		<%= link_to 'Back', logs_path %>
	</div>
</div>

app/views/logs/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2>
      View Record
      <% if @log.void_reason.present? %>
        <span class="label label-danger">VOID</span>
      <% elsif @log.present_date.present? %>
        <span class="label label-success">PRESENTED</span>
      <% end %>
    </h2>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <p>
          <strong>Chq number:</strong><br>
          <%= @log.chq_number %>
        </p>
      </div>

    <div class="col-md-4">
      <p>
        <strong>Chq date:</strong><br>
        <%= @log.chq_date %>
      </p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <p>
        <strong>Payee Name:</strong><br>
        <%= @log.payee_name %>
      </p>
    </div>
  
    <div class="col-md-4">
      <p>
        <strong>Category:</strong><br>
        <%= @log.category %>
      </p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <p>
        <strong>Deal:</strong><br>
        <%= @log.deal_id %>
      </p>
    </div>

    <div class="col-md-4">
      <p>
        <strong>Particular:</strong><br>
        <%= @log.particular %>
      </p>
    </div>
    
    <div class="col-md-4">
      <p>
        <strong>Salesperson:</strong><br>
        <%= @log.salesperson %>
      </p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <p>
        <strong>Amount:</strong><br>
        <%= @log.currencies %>
        <%= number_to_currency(@log.amount, :unit => "") %>
      </p>
    </div>

    <div class="col-md-4"></div>
    
    <div class="col-md-4">
      <strong>Voucher#:</strong><br>
      <%= @log.voucher_no %>
    </div>
  </div>  

  <p>
    <strong>Prepared by:</strong>
    <%= @log.prepared %>
  </p>

  <br>
  
  <div class="row">
    <div class="col-md-4">
      <strong>Signed Cheque Date:</strong><br>
      <%= @log.sign_date %>
    </div>

    <div class="col-md-4">
      <strong>Cheque Presented Date:</strong><br>
      <%= @log.present_date %>
    </div>

    <div class="col-md-4">
      <strong>Void Cheque Reason:</strong><br>
      <%= @log.void_reason %>
    </div>
  </div>

  
  <br>
  <br>

  <div class="panel-footer">
    <% if not current_user.viewer? %>
      <%= link_to 'Edit', edit_log_path(@log) %> |
    <% end %>
    <%= link_to 'Back', logs_path %>
  </div>
</div>